### ISSUE TITLE
createSdcObj doesn't work with tbl_df

### ISSUE THREAD

**Issue by bebru** [sdcTools/sdcMicro#223] opened 2017-06-24 17:14 UTC
Some functions from the tidyverse produce `tbl_df` instead of `data.frame`, e.g. `readr`.
`createSdcObj` returns an error if a `tbl_df` is passed to it:

```r
library(sdcMicro)
library(readr)

data(testdata)

write.csv2(testdata, file = "testdata.csv", row.names = FALSE)
testdataImp <- read_csv2(file = "testdata.csv")
file.remove("testdata.csv") # clean up

class(testdataImp)

sdcImp <- createSdcObj(testdataImp,      
                        keyVars=c('urbrur','roof','walls','water','electcon','relat','sex'),
                        numVars=c('expend','income','savings'), w='sampling_weight')
```

**Comment by bernhard-da** [comment] 2017-06-25 13:31
hi @bebru, thx for reporting. the issue is fixed in next-branch.

**Closed as completed by bernhard-da** 2017-06-25 13:31 UTC
Labels: bug, core-pkg

**Comment by bebru** [comment] 2017-06-28 11:47
Great, thanks for fixing promptly!
