### ISSUE TITLE
Wrong display of number of suppressions in sidebar in GUI

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#257] opened 2018-05-14 08:48 UTC
after applying local suppression. Instead of displaying the number of suppressions, the total number of missing values in thee variables is displayed.

Sidebar:
![schermafbeelding 2018-05-14 om 10 43 46](https://user-images.githubusercontent.com/8253935/39987151-347afe7a-5764-11e8-8605-7a1e70de321b.png)

Information on summary page:
![schermafbeelding 2018-05-14 om 10 43 58](https://user-images.githubusercontent.com/8253935/39987159-386de3bc-5764-11e8-815a-e7116a1140e2.png)

Instead of the right column the left column should be reproduced in the sidebar

**Comment by thijsbenschop** [comment] 2018-05-14 08:49
See pull request #258

**Comment by bernhard-da** [comment] 2018-05-14 09:07
@thijsbenschop  i think this behaviour is intentional and not a bug. because in `x@localSuppression$supps`, only the additional suppressions of the current run are stored and in the sidebar we want to show the total number of suppressions and not only the new ones I guess.

**Comment by thijsbenschop** [comment] 2018-05-14 09:12
@bernhard-da the column header 'suppressions' gives the impression that these values were suppressed by the local suppression algorithm. This isn't necessarily the case, however, as some values may already have been missing in the original dataset. Another option would be to change the column header to 'Total number of missings including suppressions', but doesn't a user want to know the effect of local suppression, rather than the total number of missings? We could add both to the sidebar, but I wonder whether there is sufficient space for that. 

Nevertheless, I think the current representation is wrong, as it is labelled 'Suppressions', but in fact the number of suppressions plus the number of missings per variable in the original dataset is displayed.

**Comment by bernhard-da** [comment] 2018-05-14 09:18
@thijsbenschop ok, but the column has to be renamed in either way then. Regarding https://github.com/sdcTools/sdcMicro/pull/258, the column name should probably something like ("new suppression introduced by ..."). will you update the pr?

**Comment by thijsbenschop** [comment] 2018-05-14 09:33
@bernhard-da , will do that. I also thought it may be helpful to add more information to the table on the summary page, as in the example below:

![schermafbeelding 2018-05-14 om 11 31 58](https://user-images.githubusercontent.com/8253935/39989558-956c035e-576a-11e8-852c-7381e54512d1.png)

In order to avoid confusion between suppressions and missings

**Comment by thijsbenschop** [comment] 2018-05-14 09:34
Now it looks like this:
![schermafbeelding 2018-05-14 om 11 14 20](https://user-images.githubusercontent.com/8253935/39989612-b44d8694-576a-11e8-87de-71fefe1dd8e9.png)
I also added some text

**Comment by bernhard-da** [comment] 2018-05-14 09:37
@thijsbenschop thx, this is indeed better! will merge, once you update the pr.

**Comment by thijsbenschop** [comment] 2018-05-14 09:47
@bernhard-da , just updated the pr with the additional info on the summary page and the changed column name ('Additional suppressions by local suppression algorithm')

**Comment by bernhard-da** [comment] 2018-05-14 09:54
@thijsbenschop merged, thx!

**Closed as completed by bernhard-da** 2018-05-14 09:54 UTC
Labels: enhancement, GUI

**Comment by thijsbenschop** [comment] 2018-05-15 06:02
Still one more pr #259 with two more improvements:
- column headers in summary page table
- left align values in table in sidebar, as they often aren't visible on smaller screens
