### ISSUE TITLE
seg fault error, memory not mapped

### ISSUE THREAD

**Issue by matthias-da** [sdcTools/sdcMicro#307] opened 2020-09-30 11:29 UTC
Dear C and C++ experts. 

The new version of sdcMicro lets R crashes completely with a memory not mapped error when calling createSdcObj. 
Thus the new version is currently not usable. 

```{r}
library(sdcMicro)
data(testdata)
sdc <- createSdcObj(testdata,
  keyVars=c('urbrur','roof','walls','water','electcon','relat','sex'),
  numVars=c('expend','income','savings'), w='sampling_weight')
# good bye R session
```

This was tested on Mac OS (Catalina) with R version 4.0.2.

**Comment by bernhard-da** [comment] 2020-09-30 11:47
@matthias-da can't reproduce under 4.0.2. can you provide `devtools::session_info()` ?

**Comment by matthias-da** [comment] 2020-09-30 11:55
Is listed below:
Attention - I just downgraded sdcMicro to the CRAN version, so you will now see sdcMicro not related to version 5.5.2 

Does any Mac user (Alex?) also get such an segmentation fault error?

> devtools::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS Catalina 10.15.7      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Zurich               
 date     2020-09-30                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package       * version     date       lib source                                   
 abind           1.4-5       2016-07-21 [1] CRAN (R 4.0.2)                           
 anonymizer    * 0.2.2       2020-09-21 [1] Github (paulhendricks/anonymizer@80bc634)
 assertthat      0.2.1       2019-03-21 [1] CRAN (R 4.0.2)                           
 backports       1.1.9       2020-08-24 [1] CRAN (R 4.0.2)                           
 boot            1.3-25      2020-04-26 [1] CRAN (R 4.0.2)                           
 callr           3.4.3       2020-03-28 [1] CRAN (R 4.0.2)                           
 car             3.0-9       2020-08-11 [1] CRAN (R 4.0.2)                           
 carData         3.0-4       2020-05-22 [1] CRAN (R 4.0.2)                           
 cellranger      1.1.0       2016-07-27 [1] CRAN (R 4.0.2)                           
 class           7.3-17      2020-04-26 [1] CRAN (R 4.0.2)                           
 cli             2.0.2       2020-02-28 [1] CRAN (R 4.0.2)                           
 cluster         2.1.0       2019-06-19 [1] CRAN (R 4.0.2)                           
 codetools       0.2-16      2018-12-24 [1] CRAN (R 4.0.2)                           
 coin            1.3-1       2019-08-28 [1] CRAN (R 4.0.2)                           
 colorspace      1.4-1       2019-03-18 [1] CRAN (R 4.0.2)                           
 crayon          1.3.4       2017-09-16 [1] CRAN (R 4.0.2)                           
 curl            4.3         2019-12-02 [1] CRAN (R 4.0.1)                           
 data.table    * 1.13.0      2020-07-24 [1] CRAN (R 4.0.2)                           
 DEoptimR        1.0-8       2016-11-19 [1] CRAN (R 4.0.2)                           
 desc            1.2.0       2018-05-01 [1] CRAN (R 4.0.2)                           
 devtools        2.3.1       2020-07-21 [1] CRAN (R 4.0.2)                           
 digest          0.6.25      2020-02-23 [1] CRAN (R 4.0.2)                           
 doParallel      1.0.15      2019-08-02 [1] CRAN (R 4.0.2)                           
 dplyr         * 1.0.1       2020-07-31 [1] CRAN (R 4.0.2)                           
 DT              0.15        2020-08-05 [1] CRAN (R 4.0.2)                           
 e1071           1.7-3       2019-11-26 [1] CRAN (R 4.0.2)                           
 ellipsis        0.3.1       2020-05-15 [1] CRAN (R 4.0.2)                           
 EnvStats        2.3.1       2018-07-15 [1] CRAN (R 4.0.2)                           
 evaluate        0.14        2019-05-28 [1] CRAN (R 4.0.1)                           
 fansi           0.4.1       2020-01-08 [1] CRAN (R 4.0.2)                           
 fastmap         1.0.1       2019-10-08 [1] CRAN (R 4.0.2)                           
 fitdistrplus    1.1-1       2020-05-19 [1] CRAN (R 4.0.2)                           
 forcats         0.5.0       2020-03-01 [1] CRAN (R 4.0.2)                           
 foreach         1.5.0       2020-03-30 [1] CRAN (R 4.0.2)                           
 foreign         0.8-80      2020-05-24 [1] CRAN (R 4.0.2)                           
 fs              1.5.0       2020-07-31 [1] CRAN (R 4.0.2)                           
 generics        0.0.2       2018-11-29 [1] CRAN (R 4.0.2)                           
 ggmosaic      * 0.2.0       2018-09-12 [1] CRAN (R 4.0.2)                           
 ggplot2       * 3.3.2       2020-06-19 [1] CRAN (R 4.0.2)                           
 glue            1.4.2       2020-08-27 [1] CRAN (R 4.0.2)                           
 gtable          0.3.0       2019-03-25 [1] CRAN (R 4.0.2)                           
 haven           2.3.1       2020-06-01 [1] CRAN (R 4.0.2)                           
 hms             0.5.3       2020-01-08 [1] CRAN (R 4.0.2)                           
 htmltools       0.5.0       2020-06-16 [1] CRAN (R 4.0.2)                           
 htmlwidgets     1.5.1       2019-10-08 [1] CRAN (R 4.0.2)                           
 httpuv          1.5.4       2020-06-06 [1] CRAN (R 4.0.2)                           
 httr            1.4.2       2020-07-20 [1] CRAN (R 4.0.2)                           
 iterators       1.0.12      2019-07-26 [1] CRAN (R 4.0.2)                           
 jsonlite        1.7.0       2020-06-25 [1] CRAN (R 4.0.2)                           
 knitr         * 1.29        2020-06-23 [1] CRAN (R 4.0.2)                           
 laeken          0.5.1       2020-02-05 [1] CRAN (R 4.0.2)                           
 later           1.1.0.1     2020-06-05 [1] CRAN (R 4.0.2)                           
 lattice       * 0.20-41     2020-04-02 [1] CRAN (R 4.0.2)                           
 lazyeval        0.2.2       2019-03-15 [1] CRAN (R 4.0.2)                           
 libcoin         1.0-6       2020-08-14 [1] CRAN (R 4.0.2)                           
 lifecycle       0.2.0       2020-03-06 [1] CRAN (R 4.0.2)                           
 lmtest          0.9-37      2019-04-30 [1] CRAN (R 4.0.2)                           
 logging         0.10-108    2019-07-14 [1] CRAN (R 4.0.2)                           
 magrittr        1.5         2014-11-22 [1] CRAN (R 4.0.2)                           
 MASS            7.3-51.6    2020-04-26 [1] CRAN (R 4.0.2)                           
 Matrix          1.2-18      2019-11-27 [1] CRAN (R 4.0.2)                           
 matrixStats     0.56.0      2020-03-13 [1] CRAN (R 4.0.2)                           
 memoise         1.1.0       2017-04-21 [1] CRAN (R 4.0.2)                           
 mime            0.9         2020-02-04 [1] CRAN (R 4.0.2)                           
 modeltools      0.2-23      2020-03-05 [1] CRAN (R 4.0.2)                           
 multcomp        1.4-13      2020-04-08 [1] CRAN (R 4.0.2)                           
 munsell         0.5.0       2018-06-12 [1] CRAN (R 4.0.2)                           
 mvtnorm         1.1-1       2020-06-09 [1] CRAN (R 4.0.2)                           
 nnet            7.3-14      2020-04-26 [1] CRAN (R 4.0.2)                           
 openxlsx        4.1.5       2020-05-06 [1] CRAN (R 4.0.2)                           
 pander        * 0.6.3       2018-11-06 [1] CRAN (R 4.0.2)                           
 party           1.3-5       2020-06-12 [1] CRAN (R 4.0.2)                           
 pillar          1.4.6       2020-07-10 [1] CRAN (R 4.0.2)                           
 pkgbuild        1.1.0       2020-07-13 [1] CRAN (R 4.0.2)                           
 pkgconfig       2.0.3       2019-09-22 [1] CRAN (R 4.0.2)                           
 pkgload         1.1.0       2020-05-29 [1] CRAN (R 4.0.2)                           
 plotly          4.9.2.1     2020-04-04 [1] CRAN (R 4.0.2)                           
 plyr            1.8.6       2020-03-03 [1] CRAN (R 4.0.2)                           
 prettydoc       0.4.0       2020-08-10 [1] CRAN (R 4.0.2)                           
 prettyunits     1.1.1       2020-01-24 [1] CRAN (R 4.0.2)                           
 processx        3.4.3       2020-07-05 [1] CRAN (R 4.0.2)                           
 productplots    0.1.1       2016-07-02 [1] CRAN (R 4.0.2)                           
 promises        1.1.1       2020-06-09 [1] CRAN (R 4.0.2)                           
 ps              1.3.4       2020-08-11 [1] CRAN (R 4.0.2)                           
 purrr           0.3.4       2020-04-17 [1] CRAN (R 4.0.2)                           
 R6              2.4.1       2019-11-12 [1] CRAN (R 4.0.2)                           
 ranger          0.12.1      2020-01-10 [1] CRAN (R 4.0.2)                           
 Rcpp            1.0.5       2020-07-06 [1] CRAN (R 4.0.2)                           
 RcppArmadillo   0.9.900.2.0 2020-07-17 [1] CRAN (R 4.0.2)                           
 readr         * 1.3.1       2018-12-21 [1] CRAN (R 4.0.2)                           
 readxl          1.3.1       2019-03-13 [1] CRAN (R 4.0.2)                           
 remotes         2.2.0       2020-07-21 [1] CRAN (R 4.0.2)                           
 rhandsontable   0.3.7       2018-11-20 [1] CRAN (R 4.0.2)                           
 rio             0.5.16      2018-11-26 [1] CRAN (R 4.0.2)                           
 rlang           0.4.7       2020-07-09 [1] CRAN (R 4.0.2)                           
 rmarkdown       2.3         2020-06-18 [1] CRAN (R 4.0.2)                           
 robustbase      0.93-6      2020-03-23 [1] CRAN (R 4.0.2)                           
 rprojroot       1.3-2       2018-01-03 [1] CRAN (R 4.0.2)                           
 rstudioapi      0.11        2020-02-07 [1] CRAN (R 4.0.2)                           
 sandwich        2.5-1       2019-04-06 [1] CRAN (R 4.0.2)                           
 scales          1.1.1       2020-05-11 [1] CRAN (R 4.0.2)                           
 sdcMicro      * 5.5.1       2020-02-11 [1] CRAN (R 4.0.2)                           
 sessioninfo     1.1.1       2018-11-05 [1] CRAN (R 4.0.2)                           
 shiny           1.5.0       2020-06-23 [1] CRAN (R 4.0.2)                           
 shinyBS         0.61        2015-03-31 [1] CRAN (R 4.0.2)                           
 simPop        * 1.2.0       2019-07-18 [1] CRAN (R 4.0.2)                           
 sp              1.4-2       2020-05-20 [1] CRAN (R 4.0.2)                           
 stringi         1.4.6       2020-02-17 [1] CRAN (R 4.0.2)                           
 strucchange     1.5-2       2019-10-12 [1] CRAN (R 4.0.2)                           
 survival        3.1-12      2020-04-10 [1] CRAN (R 4.0.2)                           
 testthat        2.3.2       2020-03-02 [1] CRAN (R 4.0.2)                           
 TH.data         1.0-10      2019-01-21 [1] CRAN (R 4.0.2)                           
 tibble          3.0.3       2020-07-10 [1] CRAN (R 4.0.2)                           
 tidyr           1.1.1       2020-07-31 [1] CRAN (R 4.0.2)                           
 tidyselect      1.1.0       2020-05-11 [1] CRAN (R 4.0.2)                           
 usethis         1.6.1       2020-04-29 [1] CRAN (R 4.0.2)                           
 vcd           * 1.4-7       2020-04-02 [1] CRAN (R 4.0.2)                           
 vctrs           0.3.4       2020-08-29 [1] CRAN (R 4.0.2)                           
 VIM             6.0.0       2020-05-08 [1] CRAN (R 4.0.2)                           
 viridisLite     0.3.0       2018-02-01 [1] CRAN (R 4.0.1)                           
 withr           2.2.0       2020-04-20 [1] CRAN (R 4.0.2)                           
 wrswoR          1.1.1       2020-07-26 [1] CRAN (R 4.0.2)                           
 xfun            0.16        2020-07-24 [1] CRAN (R 4.0.2)                           
 xtable          1.8-4       2019-04-21 [1] CRAN (R 4.0.2)                           
 yaml            2.2.1       2020-02-01 [1] CRAN (R 4.0.2)                           
 zip             2.1.0       2020-08-10 [1] CRAN (R 4.0.2)                           
 zoo             1.8-8       2020-05-02 [1] CRAN (R 4.0.2)

**Comment by bernhard-da** [comment] 2020-09-30 13:05
looks normal; perhaps @alexkowa can reproduce this with a mac?

**Comment by thijsbenschop** [comment] 2020-09-30 13:11
I've installed the GitHub version on Mac and don't get the error when using createSdcObj

> devtools::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS Catalina 10.15.5      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2020-09-30                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package       * version date       lib source                            
 assertthat      0.2.1   2019-03-21 [1] CRAN (R 4.0.0)                    
 backports       1.1.10  2020-09-15 [1] CRAN (R 4.0.2)                    
 callr           3.4.4   2020-09-07 [1] CRAN (R 4.0.2)                    
 carData         3.0-4   2020-05-22 [1] CRAN (R 4.0.0)                    
 cli             2.0.2   2020-02-28 [1] CRAN (R 4.0.0)                    
 cluster         2.1.0   2019-06-19 [1] CRAN (R 4.0.2)                    
 colorspace      1.4-1   2019-03-18 [1] CRAN (R 4.0.0)                    
 crayon          1.3.4   2017-09-16 [1] CRAN (R 4.0.0)                    
 curl            4.3     2019-12-02 [1] CRAN (R 4.0.0)                    
 data.table      1.13.0  2020-07-24 [1] CRAN (R 4.0.2)                    
 DEoptimR        1.0-8   2016-11-19 [1] CRAN (R 4.0.0)                    
 desc            1.2.0   2018-05-01 [1] CRAN (R 4.0.0)                    
 devtools        2.3.2   2020-09-18 [1] CRAN (R 4.0.2)                    
 digest          0.6.25  2020-02-23 [1] CRAN (R 4.0.0)                    
 dplyr           1.0.2   2020-08-18 [1] CRAN (R 4.0.2)                    
 DT              0.15    2020-08-05 [1] CRAN (R 4.0.2)                    
 ellipsis        0.3.1   2020-05-15 [1] CRAN (R 4.0.0)                    
 evaluate        0.14    2019-05-28 [1] CRAN (R 4.0.0)                    
 fansi           0.4.1   2020-01-08 [1] CRAN (R 4.0.0)                    
 fastmap         1.0.1   2019-10-08 [1] CRAN (R 4.0.0)                    
 fs              1.5.0   2020-07-31 [1] CRAN (R 4.0.2)                    
 generics        0.0.2   2018-11-29 [1] CRAN (R 4.0.0)                    
 ggplot2         3.3.2   2020-06-19 [1] CRAN (R 4.0.2)                    
 glue            1.4.2   2020-08-27 [1] CRAN (R 4.0.2)                    
 gtable          0.3.0   2019-03-25 [1] CRAN (R 4.0.0)                    
 htmltools       0.5.0   2020-06-16 [1] CRAN (R 4.0.2)                    
 htmlwidgets     1.5.1   2019-10-08 [1] CRAN (R 4.0.0)                    
 httpuv          1.5.4   2020-06-06 [1] CRAN (R 4.0.2)                    
 jsonlite        1.7.1   2020-09-07 [1] CRAN (R 4.0.2)                    
 knitr           1.30    2020-09-22 [1] CRAN (R 4.0.2)                    
 later           1.1.0.1 2020-06-05 [1] CRAN (R 4.0.2)                    
 lifecycle       0.2.0   2020-03-06 [1] CRAN (R 4.0.0)                    
 magrittr        1.5     2014-11-22 [1] CRAN (R 4.0.0)                    
 MASS            7.3-53  2020-09-09 [1] CRAN (R 4.0.2)                    
 memoise         1.1.0   2017-04-21 [1] CRAN (R 4.0.0)                    
 mime            0.9     2020-02-04 [1] CRAN (R 4.0.0)                    
 munsell         0.5.0   2018-06-12 [1] CRAN (R 4.0.0)                    
 pillar          1.4.6   2020-07-10 [1] CRAN (R 4.0.2)                    
 pkgbuild        1.1.0   2020-07-13 [1] CRAN (R 4.0.2)                    
 pkgconfig       2.0.3   2019-09-22 [1] CRAN (R 4.0.0)                    
 pkgload         1.1.0   2020-05-29 [1] CRAN (R 4.0.0)                    
 prettydoc       0.4.0   2020-08-10 [1] CRAN (R 4.0.2)                    
 prettyunits     1.1.1   2020-01-24 [1] CRAN (R 4.0.0)                    
 processx        3.4.4   2020-09-03 [1] CRAN (R 4.0.2)                    
 promises        1.1.1   2020-06-09 [1] CRAN (R 4.0.2)                    
 ps              1.3.4   2020-08-11 [1] CRAN (R 4.0.2)                    
 purrr           0.3.4   2020-04-17 [1] CRAN (R 4.0.0)                    
 R6              2.4.1   2019-11-12 [1] CRAN (R 4.0.0)                    
 Rcpp            1.0.5   2020-07-06 [1] CRAN (R 4.0.2)                    
 remotes         2.2.0   2020-07-21 [1] CRAN (R 4.0.2)                    
 rhandsontable   0.3.7   2018-11-20 [1] CRAN (R 4.0.0)                    
 rlang           0.4.7   2020-07-09 [1] CRAN (R 4.0.2)                    
 rmarkdown       2.3     2020-06-18 [1] CRAN (R 4.0.2)                    
 robustbase      0.93-6  2020-03-23 [1] CRAN (R 4.0.0)                    
 rprojroot       1.3-2   2018-01-03 [1] CRAN (R 4.0.0)                    
 rstudioapi      0.11    2020-02-07 [1] CRAN (R 4.0.0)                    
 scales          1.1.1   2020-05-11 [1] CRAN (R 4.0.0)                    
 sdcMicro      * 5.5.2   2020-09-30 [1] Github (sdcTools/sdcMicro@296ab75)
 sessioninfo     1.1.1   2018-11-05 [1] CRAN (R 4.0.0)                    
 shiny           1.5.0   2020-06-23 [1] CRAN (R 4.0.2)                    
 shinyBS         0.61    2015-03-31 [1] CRAN (R 4.0.0)                    
 testthat        2.3.2   2020-03-02 [1] CRAN (R 4.0.0)                    
 tibble          3.0.3   2020-07-10 [1] CRAN (R 4.0.2)                    
 tidyselect      1.1.0   2020-05-11 [1] CRAN (R 4.0.0)                    
 usethis         1.6.3   2020-09-17 [1] CRAN (R 4.0.2)                    
 vctrs           0.3.4   2020-08-29 [1] CRAN (R 4.0.2)                    
 withr           2.3.0   2020-09-22 [1] CRAN (R 4.0.2)                    
 xfun            0.17    2020-09-09 [1] CRAN (R 4.0.2)                    
 xtable          1.8-4   2019-04-21 [1] CRAN (R 4.0.0)                    

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

**Comment by alexkowa** [comment] 2020-09-30 14:49
Works also fine for me on Mac. So maybe just update all packages!? I just did that and it still works fine

**Comment by alexkowa** [comment] 2021-01-21 07:05
I close this now. Everything seems fine (also in R-devel). Probably it is a local issue on Matthias Mac, maybe the Xcode CLI tools are not installed properly or there is a conflict with homebrew packages...

**Closed as completed by alexkowa** 2021-01-21 07:05 UTC
