### ISSUE TITLE
Problem with sdcApp()

### ISSUE THREAD

**Issue by JM9416** [sdcTools/sdcMicro#314] opened 2021-05-13 17:49 UTC
Hello. I have an issue using sdcApp(). I cannot execute the SDC Problem (Setup SDC Problem). When I try to run it, my browser freezes and I get the follwing error:

Warning: Error in : In sliderInput(): `min`, `max`, and `value` cannot be NULL, NA, or empty.
  2: runApp
  1: sdcApp

I tried to reinstall the package and its dependencies, removing items from the global environment in R.
![freeze](https://user-images.githubusercontent.com/79281315/118165198-431e3a00-b3e1-11eb-95a2-e7e43e5f6d9c.PNG)

**Comment by bernhard-da** [comment] 2021-05-13 18:37
hi @JM9416  thx for reporting this; i think this is a duplicate of #312 which was already fixed in https://github.com/sdcTools/sdcMicro/commit/5a32b81bc20a33af0f6e78a9e14783ae852cf3d1 

we will release a new version for cran soon.

**Comment by JM9416** [comment] 2021-06-26 00:57
Can I use this package from here while you release a new version for cran?

**Comment by bernhard-da** [comment] 2021-06-26 06:22
hi @JM9416  yes, you can use the package from here;

```
# install
remotes::install_github("sdcTools/sdcMicro")

# optionally start the gui
sdcMicro::sdcApp()
```

**Closed as completed by bernhard-da** 2021-06-26 06:22 UTC
Labels: duplicate, question
