### ISSUE TITLE
GUI: Enhancement: show all warnings and error messages from console

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#120] opened 2016-11-07 20:14 UTC
There are warnings and error messages that appear in the console but not in the GUI. Should the user see all information and be informed that something went wrong, although the user might not understand what exactly went wrong? This is especially important in case of warnings, e.g. NaNs are generated.

**Comment by bernhard-da** [comment] 2016-11-07 20:17
please provide reproducable examples.

**Comment by matthias-da** [comment] 2020-09-17 13:10
Since no examples have been provided, we close this issue.

**Closed as completed by matthias-da** 2020-09-17 13:10 UTC
Labels: enhancement, awaiting feedback
