### ISSUE TITLE
Warning when running sdcApp

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#228] opened 2017-08-02 18:53 UTC
Hi,

I regularly get the following warning when running sdcApp:

```
Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```

This issue is currently discussed here: https://github.com/rstudio/DT/issues/421 and here: https://github.com/ramnathv/htmlwidgets/pull/270 and seems related to R 3.4.0.

If this is the source, a solution is also suggested. Where in the code could this happen?

**Comment by bernhard-da** [comment] 2017-08-02 19:39
not a bug. will be fixed "upstream" in DT/htmlwidgets.

**Closed as completed by bernhard-da** 2017-08-02 19:39 UTC
Labels: wontfix, GUI
