### ISSUE TITLE
Disabling server-side processing in sdcApp

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#276] opened 2019-05-10 12:17 UTC
Hi,

recently, while selecting variables in the setup-table in sdcApp, the following warning popped up in the R console:

![image](https://user-images.githubusercontent.com/8253935/57526453-bc37b200-732d-11e9-9ee4-217027773dd5.png)

Looking more closely into the renderDataTable function for this table, I noticed that in the particular case of the setup table (lines 564-573 of ui_setup_sdc.R), the default of server-side processing is overruled by the argument `server=FALSE`. What is the specific reason for disabling server-side processing for this table? In other places in the app where renderDataTable is used, the default of server-side processing is used.

![Schermafbeelding 2019-05-10 om 14 19 39](https://user-images.githubusercontent.com/8253935/57526831-c0180400-732e-11e9-8d38-b14b4c797f31.png)

Thanks,

Thijs

**Comment by GregorDeCillia** [comment] 2019-05-10 13:46
My guess is that it is because of the usage of `Shiny.UnbindAll` and `Shiny.bindAll()`. Those functions are used to create shiny input widgets inside the table cells.

We have to check if the input widgets still work after switching to server-side processing. I'll take a look at this in a few hours.

**Comment by bernhard-da** [comment] 2019-05-10 13:46
i'll have a look. i think server-side processing does not work because in this table we have the interactive selection widgets ...

**Comment by bernhard-da** [comment] 2019-05-10 13:47
ah, @GregorDeCillia was faster :)

**Comment by thijsbenschop** [comment] 2019-05-10 13:50
@GregorDeCillia and @bernhard-da , thank you for the quick reactions. 

I created a branch in my fork to test the app with server=FALSE and with some quick testing it worked. Nevertheless, I think some thorough testing is required before changing this. The issue is that with a file with many variables (around 2000), the table doesn't render and the app greys out. Perhaps changing to server-side processing would be a solution here.

I'm curious to hear what you find out about the input widgets.

**Comment by GregorDeCillia** [comment] 2019-05-10 18:14
As expected, the `server = TRUE` option in `ui_setup_dc` leads to a failing communication between the ui and the server.

https://github.com/sdcTools/sdcMicro/blob/1e252377f53b23789d75525f172cb0b3af6c3ef6/inst/shiny/sdcApp/controllers/ui_setup_sdc.R#L573-L576

To reproduce this, follow these steps

* put `server = TRUE` in the line above
* rebuild the package
* start the app with `sdcApp()`
* select `testdata` in "Microdata"
* navigate to "Anonymize"
* go back to "Microdata", and reset the dataset to `testdata2`
* go to "Anonymize"

After this, you will notice that the inputs widgets in the table are not interacting with the R session. Therefore, it is not possible to define a sdc problem now.

My interpretation is that the update of the bindings does not work properly in that case. You can also reverse the order in which the datasets are loaded. @bernhard-da @thijsbenschop can you reproduce this behavior? AFAIK, I use the most up-to-date versions of all dependency packages.

Session info: https://gist.github.com/GregorDeCillia/53b405fc6959f95d2016c18b118033ed

**Comment by bernhard-da** [comment] 2019-05-10 19:23
@GregorDeCillia yes, i can reproduce. that's why the `server=FALSE` is there. so it's not a bug i'd say.

**Comment by thijsbenschop** [comment] 2019-05-15 15:51
@GregorDeCillia and @bernhard-da, thank you for your quick reactions and explaining why server-side processing cannot be used for this table. I tested, but cannot reproduce the problem with the input widgets as you describe. However, I think it's sufficient if you experience problems to decide not to change this.

My issue wasn't meant as a bug report, but rather to understand the underlying reasons for  disabling server-side processing and perhaps finding alternatives. Unfortunately, the problem I have experienced while loading datasets in sdcApp with a large number of variables (1,738 and 12,883 observations) persists. The app gets extremely slow or breaks down. Using `server=TRUE` makes the app quicker and the following warning doesn't appear on the console.

`Listening on http://127.0.0.1:7165
Warning in instance$preRenderHook(instance) :
  It seems your data is too big for client-side DataTables. You may consider server-side processing: https://rstudio.github.io/DT/server.html`

Do you think there is a way to make the app work with `server=TRUE` or do you see alternatives?

**Comment by GregorDeCillia** [comment] 2019-05-15 18:16
One workaround is to remove unused columns from the dataset before passing it to the shiny application. If this is not feasible because all columns are needed, I suppose we could expose the server side processing as a hidden parameter. Something like

```r
options(sdcMicro_server_side_table = TRUE)
```

would be easy to implement but I'm not sure if this is a good idea from a design/maintainance perspective. What do you think @bernhard-da?

Making it work properly would require a tremendous amount of development time in my opinion.

**Comment by thijsbenschop** [comment] 2019-05-15 20:13
Thank you @GregorDeCillia, I had also thought of reducing the number of variables in the dataset, as it's very unlikely that all variables are relevant for the SDC process. Therefore, I think we can do without the extra parameter for enabling the sever side processing of the table.

Thanks for thinking along!

**Comment by GregorDeCillia** [comment] 2019-05-15 20:18
Very well. I'll close this issue for now. Feel free to reopen if the workaround of reducing the dataset is not working for you.

**Closed as completed by GregorDeCillia** 2019-05-15 20:18 UTC
