### ISSUE TITLE
bug - recode numeric to factor and group/rename

### ISSUE THREAD

**Issue by cmachingauta** [sdcTools/sdcMicro#113] opened 2016-11-01 20:35 UTC
Using caseA.dta, I recode numeric variables AGEYRS and INCWAGE to factor. I try to recode them and there is a sort of racing condition that occurs (see 7.mp4). When I restart and redo the same steps, I am able to recode AGEYRS, but the same problem occurs when I now try to recode INCWAGE, the variable name quickly defaults to AGEYRS which I just recoded. See the script attached
[recoding2.txt](https://github.com/alexkowa/sdcMicro/files/564999/recoding2.txt)

**Comment by bernhard-da** [comment] 2016-11-01 22:37
hi, please try again with the latest changes.

I changed the select input in both the microdata and sdcProblem section to a selectize-input which was the "culprit" for the race condition. Now, there is no list showing possible codes, but selecting is pretty easy and nice even for a large amount of possible values since the focus stays where it has been.

please test and check so that we can close this issue.

**Comment by cmachingauta** [comment] 2016-11-02 12:40
Thanks I tested, and that's fixed. Once the recode is done, it immediately switches to the first categorical variable on the list, in this case - REGION. Is it possible to avoid that and have it show me the variable I just recoded?

**Comment by cmachingauta** [comment] 2016-11-02 12:56
Hi, 
Now when I click on **Convert numeric variables to factor** > **Choose numeric variable  +  NO custom breaks**, and click the **Recode to factor** button, I am immediately taken to the **Analyze existing variables** window. I think something went wrong.

**Comment by bernhard-da** [comment] 2016-11-02 13:11
Hi. Please test again. After clicking the recode button, you should now stay in the currently selected variable.

As for your second problem: This is the intended behaviour and has been so since a very long time. You click the button and get to the overview page where the first variable you have selected is shown. Could you explain what has changed and/or what did you expect to have happened?

**Comment by cmachingauta** [comment] 2016-11-02 14:54
Thanks I tested the first one and that's fixed. 

RE: the second one, you are right, that's how it should be. Based on my initial reaction though, I think there is a slight disconnect and it may not immediately be obvious that you have navigated to the Explore tab. I suggest a tip/text that says along the lines of  "Click to convert and analyze converted variable(s)"

Also, I think the title could be changed to convert numeric variables into a factor, and the button also says convert, instead of recode to be consistent with what the radio button says. 

Lastly, there are no axis titles on the plot that's generated when you go to the Analyze existing variables  window after converting to factor, but there are axis titles when you convert to numeric.

**Comment by bernhard-da** [comment] 2016-11-02 15:04
Thx for testing. I agree with the text-issue which I just changed.

**Closed as completed by bernhard-da** 2016-11-02 15:04 UTC
Labels: bug, GUI
